authors/authors/urls.py
from django.contrib import admin
from django.urls import include, path
from django.urls import path
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', include('authorsapp.urls')),
    path('admin/', admin.site.urls),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

authors/authorsapp/urls.py
from django.urls import path
from . import views
from .views import register_view, login_view, my_logout
from django.contrib.auth.views import LogoutView

app_name = 'authorsapp'

urlpatterns = [
    path('', views.main, name='main'),
    path('register/', register_view, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', my_logout, name='logout'),
    path('add_author/', views.add_author, name='add_author'),
    path('author_info/<str:fullname>/', views.author_info, name='author_info'),
    path('add_quote/', views.add_quote, name='add_quote'),
]

authors/authorsapp/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField


# Create your models here.
class Author(models.Model):
    fullname = models.CharField(max_length=255)
    born_date = models.CharField(max_length=100, null=True, blank=True)
    born_location = models.CharField(max_length=255, null=True, blank=True)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.fullname


class Quote(models.Model):
    tags = ArrayField(models.CharField(max_length=30), blank=False, default=list)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, blank=True)
    quote = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return self.quote

authors/authorsapp/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Author, Quote


class RegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']
        widgets = {
            'born_date': forms.DateInput(attrs={'type': 'date'}),
        }


class QuoteForm(forms.ModelForm):
    class Meta:
        model = Quote
        fields = ['quote', 'tags', 'author']
        widgets = {
            'tags': forms.TextInput(attrs={'placeholder': 'Введите теги через запятую'}),
        }

authors/authorsapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import AuthenticationForm
from .forms import RegisterForm, AuthorForm, QuoteForm
from django.contrib.auth import logout
from .models import Author, Quote


def main(request):
    authors_arr = Author.objects.all()
    return render(request, 'authorsapp/index.html', {'authors': authors_arr})


def author_info(request, fullname):
    author = get_object_or_404(Author, fullname=fullname)
    quotes = Quote.objects.filter(author=author)
    return render(request, 'authorsapp/author_info.html', {'author': author, 'quotes': quotes})


def register_view(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('/')
    else:
        form = RegisterForm()
    return render(request, 'authorsapp/register.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('/')
    else:
        form = AuthenticationForm()
    return render(request, 'authorsapp/login.html', {'form': form})


def my_logout(request):
    logout(request)
    return redirect('/')


@login_required
def add_author(request):
    if request.method == "POST":
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
    else:
        form = AuthorForm()
    return render(request, 'authorsapp/add_author.html', {'form': form})


@login_required
def add_quote(request):
    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('authorsapp:main')
    else:
        form = QuoteForm()
    return render(request, 'authorsapp/add_quote.html', {'form': form})

authors/authorsapp/templates/authorsapp/add_author.html
{% extends "authorsapp/base.html" %}

{% block content %}
{% if user.is_authenticated %}

<h2>Add Author</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Add Author</button>
  </form>

{% endif %}
{% endblock %}

authors/authorsapp/templates/authorsapp/add_quote.html
{% extends "authorsapp/base.html" %}

{% block content %}

<h2>Додати нову цитату</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Додати цитату</button>
  </form>

{% endblock %}

authors/authorsapp/templates/authorsapp/author_info.html
{% extends "authorsapp/base.html" %}

{% block content %}

<h2>{{ author.fullname }}</h2>
<p><strong>Дата рождения:</strong> {{ author.born_date }}</p>
<p><strong>Место рождения:</strong> {{ author.born_location }}</p>
<p><strong>Описание:</strong> {{ author.description }}</p>

<h3>Цитаты:</h3>
  {% if quotes %}
    <ul>
      {% for quote in quotes %}
        <li>{{ quote.quote }}</li>
      {% endfor %}
    </ul>
  {% else %}
    <p>У этого автора пока нет цитат.</p>
  {% endif %}
{% endblock %}

authors/authorsapp/templates/authorsapp/base.html
<!doctype html>
<html lang="en" data-bs-theme="auto">
  <head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-..." crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-..." crossorigin="anonymous"></script>

      <script src="/docs/5.3/assets/js/color-modes.js"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.122.0">
    <title>Album example · Bootstrap v5.3</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/album/">



    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">

<link href="/docs/5.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.3/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.3/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.3/assets/img/favicons/safari-pinned-tab.svg" color="#712cf9">
<link rel="icon" href="/docs/5.3/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#712cf9">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
      }

      .bd-mode-toggle {
        z-index: 1500;
      }

      .bd-mode-toggle .dropdown-menu .active .bi {
        display: block !important;
      }
      .navbar-brand strong {
        font-size: 1.5rem;
        color: #ffffff;
        text-transform: uppercase;
        letter-spacing: 1px;/
      }
    </style>


  </head>
  <body>
    <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
      <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
      </symbol>
      <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
      </symbol>
      <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
      </symbol>
      <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
      </symbol>
    </svg>

<header data-bs-theme="dark">
  <div class="collapse text-bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4>About</h4>
          <p class="text-body-secondary">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4>Contact</h4>
          <ul class="list-unstyled">
            <li><a href="#" class="text-white">Follow on Twitter</a></li>
            <li><a href="#" class="text-white">Like on Facebook</a></li>
            <li><a href="#" class="text-white">Email me</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
      <a href="/" class="navbar-brand d-flex align-items-center">
        <strong>Authors</strong>
      </a>
        <div class="d-flex">
          {% if user.is_authenticated %}
            <span class="text-white me-2">Вітаю, {{ user.username }}</span>
            <form action="{% url 'authorsapp:logout' %}" method="post" style="display: inline;">
              {% csrf_token %}
              <button type="submit" class="btn btn-link">Вийти</button>
            </form>
          {% else %}
            <a href="{% url 'authorsapp:login' %}" class="btn btn-outline-light me-2">Логін</a>
            <a href="{% url 'authorsapp:register' %}" class="btn btn-primary">Реєстрація</a>
          {% endif %}
        </div>
      </button>
    </div>
  </div>
</header>
<main class="container mt-4">
{% block content %}

{% endblock %}
</main>

authors/authorsapp/templates/authorsapp/index.html
{% extends "authorsapp/base.html" %}

{% block content %}
<main>
  {% if user.is_authenticated %}
  <a href="{% url 'authorsapp:add_author' %}" class="btn btn-primary">Додати автора</a>
  <a href="{% url 'authorsapp:add_quote' %}" class="btn btn-outline-light me-2 text-dark border-primary">Додати цитату</a>
  {% endif %}
  <div class="album py-5 bg-body-tertiary">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for item in authors %}
        <div class="col">
          <div class="card shadow-sm">
            <div class="card-body">
              <h5>{{ item.fullname }}</h5>
              <p class="text">{{ item.description|slice:":140"  }}...</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a href="{% url 'authorsapp:author_info' item.fullname %}" class="btn btn-sm btn-outline-secondary">Переглянути</a>
                  {% if user.is_authenticated %}
                  <button type="button" class="btn btn-sm btn-outline-secondary">Змінити</button>
                  {% endif %}
                </div>
                {% if user.is_authenticated %}
                <button type="button" class="btn btn-sm btn-outline-secondary btn-outline-danger ">Видалити</button>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>

</main>

<footer class="text-body-secondary py-5">
  <div class="container">
    <p class="float-end mb-1">
      <a href="#">Back to top</a>
    </p>
    <p class="mb-1">Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
    <p class="mb-0">New to Bootstrap? <a href="/">Visit the homepage</a> or read our <a href="/docs/5.3/getting-started/introduction/">getting started guide</a>.</p>
  </div>
</footer>
<script src="/docs/5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    </body>
</html>
{% endblock %}

authors/authorsapp/templates/authorsapp/login.html
<!-- templates/accounts/login.html -->
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Login</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body class="bg-light">
  <div class="container mt-5">
    <h2 class="text-center">Login</h2>
    <form method="post" class="mx-auto" style="max-width: 400px;">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-primary w-100 mt-3">Login</button>
    </form>
  </div>
</body>
</html>

authors/authorsapp/templates/authorsapp/password_reset_complete.html
{% extends "authorsapp/base.html" %}

{% block content %}
  <h2>Пароль змінено!</h2>
  <p>Ваш пароль було успішно змінено. Тепер ви можете увійти, використовуючи новий пароль.</p>
  <p><a href="{% url 'login' %}">Увійти</a></p>
{% endblock %}

authors/authorsapp/templates/authorsapp/password_reset_confirm.html
{% extends "authorsapp/base.html" %}

{% block content %}
  <h2>Введіть новий пароль</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Змінити пароль</button>
  </form>
  <p><a href="{% url 'login' %}">Увійти з новим паролем</a></p>
{% endblock %}

authors/authorsapp/templates/authorsapp/password_reset_done.html
{% extends "authorsapp/base.html" %}

{% block content %}
  <h2>Перевірте свою пошту</h2>
  <p>Ми надіслали вам посилання для відновлення паролю на вказану адресу електронної пошти.</p>
  <p>Якщо ви не отримали листа, перевірте спам або <a href="{% url 'password_reset' %}">спробуйте ще раз</a>.</p>
{% endblock %}

authors/authorsapp/templates/authorsapp/password_reset_form.html
{% extends "authorsapp/base.html" %}

{% block content %}
  <h2>Відновлення паролю</h2>
  <p>Введіть свій email, і ми надішлемо вам посилання для відновлення паролю.</p>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Відправити посилання для відновлення паролю</button>
  </form>
  <p>Пам'ятаєте пароль? <a href="{% url 'login' %}">Увійти</a></p>
{% endblock %}

authors/authorsapp/templates/authorsapp/register.html
<!-- templates/accounts/register.html -->
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Register</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body class="bg-light">
  <div class="container mt-5">
    <h2 class="text-center">Register</h2>
    <form method="post" class="mx-auto" style="max-width: 400px;">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-primary w-100 mt-3">Register</button>
    </form>
  </div>
</body>
</html>